### PR TITLE
feat: BIBO: The Bibliographic Ontology

### PR DESCRIPTION
**Pull request by tpluscode**

### CODE REVIEW

**Comment by tpluscode** [comment]
BIBO comes with a ton of terms imported from other vocabs. Do we keep that?

**Comment by ktk** [comment]
@tpluscode thanks for noticing, no we should filter that all out. that's really not a nice thing to do

**Comment by tpluscode** [comment]
But how @ktk?

It contains legitimate assertions like 

```turtle
prism1:volume a owl:DatatypeProperty ;
    owl:equivalentProperty bibo:volume .
```

But also more weird stuff like 

```turtle
dcterms:Agent a owl:Class ;
    owl:equivalentClass foaf:Agent ;
    skos:editorialNote """BIBO assert that a dcterms:Agent is an equivalent class to foaf:Agent.
This means that all the individuals belonging to the foaf:Agent class
also belongs to the dcterms:Agent class. This way, dcterms:contributor
can be used on foaf:Person, foaf:Organization, foaf:Agent and foaf:Group.
Even if this link is not done in neither the FOAF nor the DCTERMS ontologies this is a wide spread fact that is asserted by BIBO."""@en .
```

**Comment by vhf** [comment]
IMO we should keep the ontologies as-is and leave it up to the users of this package to filter out what they don't want. The misplaced triples in an ontology won't pollute other ontologies because this package packs each ontology in its own graph or dataset.

For instance the prefix-server only shows the terms that an ontology should define, ie. in `schema:` it filters out triples which subjects don't start with `https://schema.org/`.

**Comment by ktk** [comment]
I agree that this is ok for rdf-vocabulary itself but there is really a ton of triples in there that re-defines other terms, as subject URIs. It might be the same like the official definition but I'm not happy with it as it might introduce confusion. Not sure what to do now though.

**Pull request merged**
