### PR TITLE
Add SEM, issue #34

### PR DESCRIPTION
**Pull request by ktk**

### CODE REVIEW

**Comment by ktk** [comment]
I just noticed that the ontology itself is missing, looks like sometimes it works and other times it creates an error message. Can you check that on your system @vhf ? Not sure what is going wrong here

**Comment by vhf** [comment]
There seems to be problems parsing this: https://semanticweb.cs.vu.nl/2009/11/sem/sem.rdf

Could you please try parsing it with other tools to check if it's valid at all? I'm a bit confused by the `&sem;`, `&rdf;` prefixes

**Comment by ktk** [comment]
Yeah very strange, saw this too. Weird thing is that it does work every once in a while. I manually downloaded the file and tried it with various parsers, always worked out well and no errors reported. Is it possible that we don't always get the same response back?

**Comment by ktk** [comment]
Maybe @rubensworks could check out the file as well?

**Comment by rubensworks** [comment]
I just tried it myself, and that file is being parsed just fine here. The only way I can make it error is by omitting the `baseIRI`, is it possible that you forgot to pass it?

**Comment by vhf** [comment]
Thanks @rubensworks ! Yeah we're definitely not passing any baseIRI: https://github.com/zazuko/rdf-vocabularies/blob/master/fetch.js#L7

I'll find a way

**Comment by vhf** [comment]
@rubensworks I tried this:
```js
new RdfXmlParser({
  allowDuplicateRdfIds: true,
  baseIRI: 'http://semanticweb.cs.vu.nl/2009/11/sem/'
})
```
but I'm still getting `Invalid URI: &rdf;RDF`. Any idea why? Could you please share what you did to make it work?

**Comment by rubensworks** [comment]
I just tried again, and I was having the same problem as you. I was probably testing with the wrong input file before, my apologies.

The problem was that [doctype entity parsing was too strict](https://github.com/rdfjs/rdfxml-streaming-parser.js/commit/d6b23309f77027bd7405ea9d3ae9e066e366e1a8), and failed for this document. I've fixed it in release 1.3.1.

**Comment by vhf** [comment]
Great, thanks a lot @rubensworks :)

**Comment by vhf** [comment]
@ktk please review the quads

**Comment by ktk** [comment]
LGTM!

**Pull request merged**
